#POSTGRES Connection
#==========================================================
spring.application.name=spriced-meritor-outbound
spring.datasource.url=jdbc:postgresql://172.26.211.190:5433/spriced_meritor
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
#==========================================================

camel.springboot.main-run-controller=true

#SFTP Connection
#===============================
SFTP.HOST=106.51.91.59
SFTP.USER=cfg
SFTP.PRIVATE.KEY=C:/Users/srinath.venugopal_si/Keys/id_rsa
PASSPHRASE=simkey
DESTINATION=/meritor/outbound/
SFTP.PORT=22
#===============================

#FILEPATHS
#============================
FILE.PATH=file:///C://file_storage/OutboundFiles/
COMPRESSED.FILE.PATH=file:///C://file_storage//OutboundFiles//CompressedFiles//
ENCRYPTED.FILE.PATH=file:///C://file_storage//OutboundFiles//EncryptedFiles//

#============================

POLL.ENRICH.SETTINGS=&move=processed&idempotent=true

#PGP
#===============================
#PGP.KEY.PATH=file:///C:/Users/muham/Downloads/Asif Azmi_0xF4F99C5C_public.asc
#PGP.PASSPHRASE=simai2024
#PGP.EMAIL=asif.azmi@simadvisorypartner.com

#PGP.PASSPHRASE=simkey2024
#PGP.KEY.PATH=file:///C:/Users/srinath.venugopal_si/Documents/publickey.asc

PGP.KEY.PATH=file:///C://Users//srinath.venugopal_si//Downloads//public_meritor.pgp
PGP.KEY.PATH.ORACLE=file:///C://Users//srinath.venugopal_si//Downloads//oracle.gpg
PGP.EMAIL.ORACLE=oracle@ftizsldmwapp103.ftiz.cummins.com

#oracle@ftizsldmwapp103.ftiz.cummins.com
#b2bgroup@meritor.com

PGP.EMAIL=b2bgroup@meritor.com
#===============================


logging.level.root=INFO
logging.level.org.apache.camel=INFO
logging.level.org.apache.camel.component.sftp=DEBUG
